### ISSUE TITLE
All constructors on the PrivataAudit class are `protected`

### ISSUE THREAD

**Issue by micklynch** [blockbirdLabs/data-java-sdk#18]
@pedrocrvz , all the constructors on PrivataAudit are protected so I can't initialize. We can either make the constructors `public` or create a `static` method for getting the instantiated class. I guess that was what we were talking about yesterday but I didn't notice it until now.

**Comment by pedrocrvz** [comment]
We should make it public, yes. I don't remember why I left them protected. I will do a PR now.
